Get incompatible rsc.io/sampler
  hnkamur@primergy:~/go-mod-docker-experiment$ docker build -t hnakamur/go-mod-exp .
  Sending build context to Docker daemon    128kB
  Step 1/7 : From golang:1.12 as builder
   ---> 36e5881731e4
  Step 2/7 : WORKDIR /src/app
   ---> Using cache
   ---> 1524063c47f7
  Step 3/7 : COPY go.mod go.sum ./
   ---> 9b968e926889
  Step 4/7 : RUN go mod download
   ---> Running in f1369b4174ab
  go: finding golang.org/x/text v0.3.0
  go: finding rsc.io/quote v1.5.2
  go: finding rsc.io/sampler v1.3.0
  go: finding golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
  Removing intermediate container f1369b4174ab
   ---> f1c78a528e5a
  Step 5/7 : COPY hello.go hello_test.go ./
   ---> b70ebe59d1f7
  Step 6/7 : RUN go get rsc.io/sampler
   ---> Running in 62be9eb754b4
  go: finding rsc.io/sampler v1.99.99
  go: downloading rsc.io/sampler v1.99.99
  go: extracting rsc.io/sampler v1.99.99
  Removing intermediate container 62be9eb754b4
   ---> b57f295036eb
  Step 7/7 : CMD ["/bin/sh"]
   ---> Running in 632ecb66f450
  Removing intermediate container 632ecb66f450
   ---> e83df09b7bba
  Successfully built e83df09b7bba
  Successfully tagged hnakamur/go-mod-exp:latest
  hnakamur@primergy:~/go-mod-docker-experiment$ docker run --rm -it hnakamur/go-mod-exp
  # go test
  --- FAIL: TestHello (0.00s)
      hello_test.go:8: Hello() = "99 bottles of beer on the wall, 99 bottles of beer, ...", want "Hello, world."
  FAIL
  exit status 1
  FAIL    example.com/hello       0.001s
  # go list -m -versions rsc.io/sampler
  rsc.io/sampler v1.0.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.99.99
  # cat go.mod
  module example.com/hello

  go 1.12

  require (
          golang.org/x/text v0.3.0 // indirect
          rsc.io/quote v1.5.2
          rsc.io/sampler v1.99.99 // indirect
  )
  # cat go.sum
  golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c h1:qgOY6WgZOaTkIIMiVjBQcw93ERBE4m30iBm00nkL0i8=
  golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
  golang.org/x/text v0.3.0 h1:g61tztE5qeGQ89tm6NTjjM9VPIm088od1l6aSorWRWg=
  golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
  rsc.io/quote v1.5.2 h1:w5fcysjrx7yqtD/aO+QwRjYZOKnaM9Uh2b40tElTs3Y=
  rsc.io/quote v1.5.2/go.mod h1:LzX7hefJvL54yjefDEDHNONDjII0t9xZLPXsUe+TKr0=
  rsc.io/sampler v1.3.0 h1:7uVkIFmeBqHfdjD+gZwtXXI+RODJ2Wc4O7MPEh/QiW4=
  rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
  rsc.io/sampler v1.99.99 h1:7i08f/p5TBU5joCPW3GjWG1ZFCmr28ybGqlXtelhEK8=
  rsc.io/sampler v1.99.99/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
  # go get rsc.io/sampler@v1.3.1
  go: finding rsc.io/sampler v1.3.1
  go: downloading rsc.io/sampler v1.3.1
  go: extracting rsc.io/sampler v1.3.1
  # cat go.mod
  module example.com/hello

  go 1.12

  require (
          golang.org/x/text v0.3.0 // indirect
          rsc.io/quote v1.5.2
          rsc.io/sampler v1.3.1 // indirect
  )
  # cat go.sum
  golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c h1:qgOY6WgZOaTkIIMiVjBQcw93ERBE4m30iBm00nkL0i8=
  golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
  golang.org/x/text v0.3.0 h1:g61tztE5qeGQ89tm6NTjjM9VPIm088od1l6aSorWRWg=
  golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
  rsc.io/quote v1.5.2 h1:w5fcysjrx7yqtD/aO+QwRjYZOKnaM9Uh2b40tElTs3Y=
  rsc.io/quote v1.5.2/go.mod h1:LzX7hefJvL54yjefDEDHNONDjII0t9xZLPXsUe+TKr0=
  rsc.io/sampler v1.3.0 h1:7uVkIFmeBqHfdjD+gZwtXXI+RODJ2Wc4O7MPEh/QiW4=
  rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
  rsc.io/sampler v1.3.1 h1:F0c3J2nQCdk9ODsNhU3sElnvPIxM/xV1c/qZuAeZmac=
  rsc.io/sampler v1.3.1/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
  rsc.io/sampler v1.99.99 h1:7i08f/p5TBU5joCPW3GjWG1ZFCmr28ybGqlXtelhEK8=
  rsc.io/sampler v1.99.99/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
  # go test
  PASS
  ok      example.com/hello       0.002s